version: "3.9"
services:

  rstudio:
    build: .
    environment:
      - AWS_PROFILE=${AWS_PROFILE-default}
      - AWS_REGION="us-east-2"
      - DISABLE_AUTH=true
      - ROOT=TRUE
      # - MORNINGSTAR_API_USER=mthomson@sysotechnologies.com
      # - MORNINGSTAR_API_PWD=l8lY2#w2uXIVkHl^UDMdqt^
    volumes:
      - ~/Code/sysotech:/home/rstudio
      - ~/.aws:/home/rstudio/.aws
      - ./.Renviron:/home/rstudio/.Renviron
      - ~/.bashrc:/home/rstudio/.bashrc
      - ./site-library:/usr/local/lib/R/site-library  # Shared libraries
      # - ${LIBPATH}:/usr/local/lib/R/library  # Project-specific library
    ports:
      - 127.0.0.1:8787:8787

